shell fish

# Англійська розкладка
map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard

# Українська розкладка (літери С та М)
map ctrl+с copy_and_clear_or_interrupt
map ctrl+С copy_and_clear_or_interrupt
map ctrl+м paste_from_clipboard
map ctrl+М paste_from_clipboard




# BEGIN_KITTY_THEME
# bl1nk
include current-theme.conf
# END_KITTY_THEME