source = ~/.config/hypr/hyprtoolkit.conf

general {
    grab_focus = true
}

cache {
    enabled = true
}

finders {
    default_finder = desktop
    math_prefix = =
    unicode_prefix = .
    desktop_icons = true
}

ui {
    window_size = 450 350
}