background = 0xCC1A2014
base = 0xCC2B362C
text = 0xFFE2E4D1
accent = 0xFF86A650
accent_secondary = 0xFFC6CE9D

font_family = JetBrainsMono Nerd Font
font_size = 12

icon_theme = Slot-Dark-Icons

rounding_large = 12
rounding_small = 8