local s = require("modules.env")
hl.env("XCURSOR_THEME", s.cursorTheme)
hl.env("XCURSOR_SIZE", s.cursorSize)
hl.env("HYPRCURSOR_SIZE", s.cursorSize)

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl setcursor " .. s.cursorTheme .. " " .. s.cursorSize)
    hl.exec_cmd("sleep 2 && waybar")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("[workspace 2 silent] " .. s.browser)
    hl.exec_cmd("[workspace 1 silent] Telegram &")
    hl.exec_cmd("[workspace 1 silent] kitty -e subtui")
end)